databases:
  - name: dorel
    databaseName: dorel
    user: dorel

services:
  - type: web
    name: dorel
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dorel
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false